// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/comment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 错误码定义 (区间: 40000-49999)
type CommentErrorCode int32

const (
	CommentErrorCode_COMMENT_SUCCESS        CommentErrorCode = 0
	CommentErrorCode_COMMENT_NOT_FOUND      CommentErrorCode = 40001
	CommentErrorCode_COMMENT_CREATE_FAILED  CommentErrorCode = 40011
	CommentErrorCode_COMMENT_UPDATE_FAILED  CommentErrorCode = 40012
	CommentErrorCode_COMMENT_DELETE_FAILED  CommentErrorCode = 40013
	CommentErrorCode_COMMENT_LIST_FAILED    CommentErrorCode = 40014
	CommentErrorCode_COMMENT_ENABLE_FAILED  CommentErrorCode = 40015
	CommentErrorCode_COMMENT_DISABLE_FAILED CommentErrorCode = 40016
)

// Enum value maps for CommentErrorCode.
var (
	CommentErrorCode_name = map[int32]string{
		0:     "COMMENT_SUCCESS",
		40001: "COMMENT_NOT_FOUND",
		40011: "COMMENT_CREATE_FAILED",
		40012: "COMMENT_UPDATE_FAILED",
		40013: "COMMENT_DELETE_FAILED",
		40014: "COMMENT_LIST_FAILED",
		40015: "COMMENT_ENABLE_FAILED",
		40016: "COMMENT_DISABLE_FAILED",
	}
	CommentErrorCode_value = map[string]int32{
		"COMMENT_SUCCESS":        0,
		"COMMENT_NOT_FOUND":      40001,
		"COMMENT_CREATE_FAILED":  40011,
		"COMMENT_UPDATE_FAILED":  40012,
		"COMMENT_DELETE_FAILED":  40013,
		"COMMENT_LIST_FAILED":    40014,
		"COMMENT_ENABLE_FAILED":  40015,
		"COMMENT_DISABLE_FAILED": 40016,
	}
)

func (x CommentErrorCode) Enum() *CommentErrorCode {
	p := new(CommentErrorCode)
	*p = x
	return p
}

func (x CommentErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommentErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_comment_proto_enumTypes[0].Descriptor()
}

func (CommentErrorCode) Type() protoreflect.EnumType {
	return &file_proto_comment_proto_enumTypes[0]
}

func (x CommentErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommentErrorCode.Descriptor instead.
func (CommentErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{0}
}

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ArticleId     uint32                 `protobuf:"varint,2,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ParentId      uint32                 `protobuf:"varint,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     uint32                 `protobuf:"varint,9,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReplyCount    uint32                 `protobuf:"varint,10,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	Status        uint32                 `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Replies       []*Comment             `protobuf:"bytes,14,rep,name=replies,proto3" json:"replies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_proto_comment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Comment) GetArticleId() uint32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *Comment) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Comment) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Comment) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Comment) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Comment) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *Comment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Comment) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Comment) GetReplyCount() uint32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Comment) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Comment) GetReplies() []*Comment {
	if x != nil {
		return x.Replies
	}
	return nil
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint32                 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentId      uint32                 `protobuf:"varint,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentRequest) GetArticleId() uint32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *CreateCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() uint32 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comment       *Comment               `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type GetCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint32                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRequest) Reset() {
	*x = GetCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRequest) ProtoMessage() {}

func (x *GetCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{3}
}

func (x *GetCommentRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

type GetCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comment       *Comment               `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentResponse) Reset() {
	*x = GetCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentResponse) ProtoMessage() {}

func (x *GetCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentResponse.ProtoReflect.Descriptor instead.
func (*GetCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type UpdateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint32                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentRequest) Reset() {
	*x = UpdateCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentRequest) ProtoMessage() {}

func (x *UpdateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCommentRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *UpdateCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type UpdateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comment       *Comment               `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommentResponse) Reset() {
	*x = UpdateCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommentResponse) ProtoMessage() {}

func (x *UpdateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommentResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdateCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint32                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin       uint32                 `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteCommentRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *DeleteCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteCommentRequest) GetIsAdmin() uint32 {
	if x != nil {
		return x.IsAdmin
	}
	return 0
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	UserId        uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_proto_comment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{9}
}

func (x *ListCommentsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCommentsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCommentsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comments      []*Comment             `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_proto_comment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{10}
}

func (x *ListCommentsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListCommentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetArticleCommentsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ArticleId      uint32                 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Page           uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize       uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	IncludeReplies bool                   `protobuf:"varint,4,opt,name=include_replies,json=includeReplies,proto3" json:"include_replies,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetArticleCommentsRequest) Reset() {
	*x = GetArticleCommentsRequest{}
	mi := &file_proto_comment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleCommentsRequest) ProtoMessage() {}

func (x *GetArticleCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleCommentsRequest.ProtoReflect.Descriptor instead.
func (*GetArticleCommentsRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{11}
}

func (x *GetArticleCommentsRequest) GetArticleId() uint32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *GetArticleCommentsRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetArticleCommentsRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetArticleCommentsRequest) GetIncludeReplies() bool {
	if x != nil {
		return x.IncludeReplies
	}
	return false
}

type GetArticleCommentsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Comments       []*Comment             `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	Total          uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	CommentEnabled bool                   `protobuf:"varint,5,opt,name=comment_enabled,json=commentEnabled,proto3" json:"comment_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetArticleCommentsResponse) Reset() {
	*x = GetArticleCommentsResponse{}
	mi := &file_proto_comment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleCommentsResponse) ProtoMessage() {}

func (x *GetArticleCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleCommentsResponse.ProtoReflect.Descriptor instead.
func (*GetArticleCommentsResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{12}
}

func (x *GetArticleCommentsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetArticleCommentsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetArticleCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *GetArticleCommentsResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetArticleCommentsResponse) GetCommentEnabled() bool {
	if x != nil {
		return x.CommentEnabled
	}
	return false
}

type ReplyCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint32                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCommentRequest) Reset() {
	*x = ReplyCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCommentRequest) ProtoMessage() {}

func (x *ReplyCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCommentRequest.ProtoReflect.Descriptor instead.
func (*ReplyCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyCommentRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *ReplyCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReplyCommentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type ReplyCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Reply         *Comment               `protobuf:"bytes,3,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyCommentResponse) Reset() {
	*x = ReplyCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyCommentResponse) ProtoMessage() {}

func (x *ReplyCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyCommentResponse.ProtoReflect.Descriptor instead.
func (*ReplyCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{14}
}

func (x *ReplyCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReplyCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReplyCommentResponse) GetReply() *Comment {
	if x != nil {
		return x.Reply
	}
	return nil
}

type LikeCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint32                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentRequest) Reset() {
	*x = LikeCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentRequest) ProtoMessage() {}

func (x *LikeCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentRequest.ProtoReflect.Descriptor instead.
func (*LikeCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{15}
}

func (x *LikeCommentRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *LikeCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type LikeCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	LikeCount     uint32                 `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeCommentResponse) Reset() {
	*x = LikeCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeCommentResponse) ProtoMessage() {}

func (x *LikeCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeCommentResponse.ProtoReflect.Descriptor instead.
func (*LikeCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{16}
}

func (x *LikeCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LikeCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LikeCommentResponse) GetLikeCount() uint32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

type GetCommentRepliesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     uint32                 `protobuf:"varint,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	Page          uint32                 `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRepliesRequest) Reset() {
	*x = GetCommentRepliesRequest{}
	mi := &file_proto_comment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRepliesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRepliesRequest) ProtoMessage() {}

func (x *GetCommentRepliesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRepliesRequest.ProtoReflect.Descriptor instead.
func (*GetCommentRepliesRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{17}
}

func (x *GetCommentRepliesRequest) GetCommentId() uint32 {
	if x != nil {
		return x.CommentId
	}
	return 0
}

func (x *GetCommentRepliesRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommentRepliesRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCommentRepliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Replies       []*Comment             `protobuf:"bytes,3,rep,name=replies,proto3" json:"replies,omitempty"`
	Total         uint32                 `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommentRepliesResponse) Reset() {
	*x = GetCommentRepliesResponse{}
	mi := &file_proto_comment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommentRepliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommentRepliesResponse) ProtoMessage() {}

func (x *GetCommentRepliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommentRepliesResponse.ProtoReflect.Descriptor instead.
func (*GetCommentRepliesResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{18}
}

func (x *GetCommentRepliesResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCommentRepliesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCommentRepliesResponse) GetReplies() []*Comment {
	if x != nil {
		return x.Replies
	}
	return nil
}

func (x *GetCommentRepliesResponse) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type EnableCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint32                 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCommentRequest) Reset() {
	*x = EnableCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCommentRequest) ProtoMessage() {}

func (x *EnableCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCommentRequest.ProtoReflect.Descriptor instead.
func (*EnableCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{19}
}

func (x *EnableCommentRequest) GetArticleId() uint32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *EnableCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type EnableCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnableCommentResponse) Reset() {
	*x = EnableCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnableCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableCommentResponse) ProtoMessage() {}

func (x *EnableCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableCommentResponse.ProtoReflect.Descriptor instead.
func (*EnableCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{20}
}

func (x *EnableCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EnableCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisableCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     uint32                 `protobuf:"varint,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCommentRequest) Reset() {
	*x = DisableCommentRequest{}
	mi := &file_proto_comment_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCommentRequest) ProtoMessage() {}

func (x *DisableCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCommentRequest.ProtoReflect.Descriptor instead.
func (*DisableCommentRequest) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{21}
}

func (x *DisableCommentRequest) GetArticleId() uint32 {
	if x != nil {
		return x.ArticleId
	}
	return 0
}

func (x *DisableCommentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type DisableCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisableCommentResponse) Reset() {
	*x = DisableCommentResponse{}
	mi := &file_proto_comment_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisableCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableCommentResponse) ProtoMessage() {}

func (x *DisableCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_comment_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableCommentResponse.ProtoReflect.Descriptor instead.
func (*DisableCommentResponse) Descriptor() ([]byte, []int) {
	return file_proto_comment_proto_rawDescGZIP(), []int{22}
}

func (x *DisableCommentResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DisableCommentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_comment_proto protoreflect.FileDescriptor

const file_proto_comment_proto_rawDesc = "" +
	"\n" +
	"\x13proto/comment.proto\x12\n" +
	"comment.v1\"\x9d\x03\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"article_id\x18\x02 \x01(\rR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\rR\bparentId\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\t \x01(\rR\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\n" +
	" \x01(\rR\n" +
	"replyCount\x12\x16\n" +
	"\x06status\x18\v \x01(\rR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12-\n" +
	"\areplies\x18\x0e \x03(\v2\x13.comment.v1.CommentR\areplies\"\x85\x01\n" +
	"\x14CreateCommentRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\rR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\rR\bparentId\"t\n" +
	"\x15CreateCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\acomment\x18\x03 \x01(\v2\x13.comment.v1.CommentR\acomment\"2\n" +
	"\x11GetCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\rR\tcommentId\"q\n" +
	"\x12GetCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\acomment\x18\x03 \x01(\v2\x13.comment.v1.CommentR\acomment\"h\n" +
	"\x14UpdateCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\rR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"t\n" +
	"\x15UpdateCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\acomment\x18\x03 \x01(\v2\x13.comment.v1.CommentR\acomment\"i\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\rR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\rR\aisAdmin\"E\n" +
	"\x15DeleteCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"_\n" +
	"\x13ListCommentsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"\x8b\x01\n" +
	"\x14ListCommentsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\bcomments\x18\x03 \x03(\v2\x13.comment.v1.CommentR\bcomments\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"\x94\x01\n" +
	"\x19GetArticleCommentsRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\rR\tarticleId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\x12'\n" +
	"\x0finclude_replies\x18\x04 \x01(\bR\x0eincludeReplies\"\xba\x01\n" +
	"\x1aGetArticleCommentsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\bcomments\x18\x03 \x03(\v2\x13.comment.v1.CommentR\bcomments\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\x12'\n" +
	"\x0fcomment_enabled\x18\x05 \x01(\bR\x0ecommentEnabled\"g\n" +
	"\x13ReplyCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\rR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\"o\n" +
	"\x14ReplyCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x05reply\x18\x03 \x01(\v2\x13.comment.v1.CommentR\x05reply\"L\n" +
	"\x12LikeCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\rR\tcommentId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"b\n" +
	"\x13LikeCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\rR\tlikeCount\"j\n" +
	"\x18GetCommentRepliesRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\rR\tcommentId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\rR\bpageSize\"\x8e\x01\n" +
	"\x19GetCommentRepliesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12-\n" +
	"\areplies\x18\x03 \x03(\v2\x13.comment.v1.CommentR\areplies\x12\x14\n" +
	"\x05total\x18\x04 \x01(\rR\x05total\"N\n" +
	"\x14EnableCommentRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\rR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"E\n" +
	"\x15EnableCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"O\n" +
	"\x15DisableCommentRequest\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\rR\tarticleId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"F\n" +
	"\x16DisableCommentResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xed\x01\n" +
	"\x10CommentErrorCode\x12\x13\n" +
	"\x0fCOMMENT_SUCCESS\x10\x00\x12\x17\n" +
	"\x11COMMENT_NOT_FOUND\x10\xc1\xb8\x02\x12\x1b\n" +
	"\x15COMMENT_CREATE_FAILED\x10˸\x02\x12\x1b\n" +
	"\x15COMMENT_UPDATE_FAILED\x10̸\x02\x12\x1b\n" +
	"\x15COMMENT_DELETE_FAILED\x10\u0378\x02\x12\x19\n" +
	"\x13COMMENT_LIST_FAILED\x10θ\x02\x12\x1b\n" +
	"\x15COMMENT_ENABLE_FAILED\x10ϸ\x02\x12\x1c\n" +
	"\x16COMMENT_DISABLE_FAILED\x10и\x022\xcb\a\n" +
	"\x0eCommentService\x12T\n" +
	"\rCreateComment\x12 .comment.v1.CreateCommentRequest\x1a!.comment.v1.CreateCommentResponse\x12K\n" +
	"\n" +
	"GetComment\x12\x1d.comment.v1.GetCommentRequest\x1a\x1e.comment.v1.GetCommentResponse\x12T\n" +
	"\rUpdateComment\x12 .comment.v1.UpdateCommentRequest\x1a!.comment.v1.UpdateCommentResponse\x12T\n" +
	"\rDeleteComment\x12 .comment.v1.DeleteCommentRequest\x1a!.comment.v1.DeleteCommentResponse\x12Q\n" +
	"\fListComments\x12\x1f.comment.v1.ListCommentsRequest\x1a .comment.v1.ListCommentsResponse\x12c\n" +
	"\x12GetArticleComments\x12%.comment.v1.GetArticleCommentsRequest\x1a&.comment.v1.GetArticleCommentsResponse\x12Q\n" +
	"\fReplyComment\x12\x1f.comment.v1.ReplyCommentRequest\x1a .comment.v1.ReplyCommentResponse\x12N\n" +
	"\vLikeComment\x12\x1e.comment.v1.LikeCommentRequest\x1a\x1f.comment.v1.LikeCommentResponse\x12`\n" +
	"\x11GetCommentReplies\x12$.comment.v1.GetCommentRepliesRequest\x1a%.comment.v1.GetCommentRepliesResponse\x12T\n" +
	"\rEnableComment\x12 .comment.v1.EnableCommentRequest\x1a!.comment.v1.EnableCommentResponse\x12W\n" +
	"\x0eDisableComment\x12!.comment.v1.DisableCommentRequest\x1a\".comment.v1.DisableCommentResponseB.Z,github.com/mysunshines/blog-comment/proto/pbb\x06proto3"

var (
	file_proto_comment_proto_rawDescOnce sync.Once
	file_proto_comment_proto_rawDescData []byte
)

func file_proto_comment_proto_rawDescGZIP() []byte {
	file_proto_comment_proto_rawDescOnce.Do(func() {
		file_proto_comment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_comment_proto_rawDesc), len(file_proto_comment_proto_rawDesc)))
	})
	return file_proto_comment_proto_rawDescData
}

var file_proto_comment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_comment_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_comment_proto_goTypes = []any{
	(CommentErrorCode)(0),              // 0: comment.v1.CommentErrorCode
	(*Comment)(nil),                    // 1: comment.v1.Comment
	(*CreateCommentRequest)(nil),       // 2: comment.v1.CreateCommentRequest
	(*CreateCommentResponse)(nil),      // 3: comment.v1.CreateCommentResponse
	(*GetCommentRequest)(nil),          // 4: comment.v1.GetCommentRequest
	(*GetCommentResponse)(nil),         // 5: comment.v1.GetCommentResponse
	(*UpdateCommentRequest)(nil),       // 6: comment.v1.UpdateCommentRequest
	(*UpdateCommentResponse)(nil),      // 7: comment.v1.UpdateCommentResponse
	(*DeleteCommentRequest)(nil),       // 8: comment.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil),      // 9: comment.v1.DeleteCommentResponse
	(*ListCommentsRequest)(nil),        // 10: comment.v1.ListCommentsRequest
	(*ListCommentsResponse)(nil),       // 11: comment.v1.ListCommentsResponse
	(*GetArticleCommentsRequest)(nil),  // 12: comment.v1.GetArticleCommentsRequest
	(*GetArticleCommentsResponse)(nil), // 13: comment.v1.GetArticleCommentsResponse
	(*ReplyCommentRequest)(nil),        // 14: comment.v1.ReplyCommentRequest
	(*ReplyCommentResponse)(nil),       // 15: comment.v1.ReplyCommentResponse
	(*LikeCommentRequest)(nil),         // 16: comment.v1.LikeCommentRequest
	(*LikeCommentResponse)(nil),        // 17: comment.v1.LikeCommentResponse
	(*GetCommentRepliesRequest)(nil),   // 18: comment.v1.GetCommentRepliesRequest
	(*GetCommentRepliesResponse)(nil),  // 19: comment.v1.GetCommentRepliesResponse
	(*EnableCommentRequest)(nil),       // 20: comment.v1.EnableCommentRequest
	(*EnableCommentResponse)(nil),      // 21: comment.v1.EnableCommentResponse
	(*DisableCommentRequest)(nil),      // 22: comment.v1.DisableCommentRequest
	(*DisableCommentResponse)(nil),     // 23: comment.v1.DisableCommentResponse
}
var file_proto_comment_proto_depIdxs = []int32{
	1,  // 0: comment.v1.Comment.replies:type_name -> comment.v1.Comment
	1,  // 1: comment.v1.CreateCommentResponse.comment:type_name -> comment.v1.Comment
	1,  // 2: comment.v1.GetCommentResponse.comment:type_name -> comment.v1.Comment
	1,  // 3: comment.v1.UpdateCommentResponse.comment:type_name -> comment.v1.Comment
	1,  // 4: comment.v1.ListCommentsResponse.comments:type_name -> comment.v1.Comment
	1,  // 5: comment.v1.GetArticleCommentsResponse.comments:type_name -> comment.v1.Comment
	1,  // 6: comment.v1.ReplyCommentResponse.reply:type_name -> comment.v1.Comment
	1,  // 7: comment.v1.GetCommentRepliesResponse.replies:type_name -> comment.v1.Comment
	2,  // 8: comment.v1.CommentService.CreateComment:input_type -> comment.v1.CreateCommentRequest
	4,  // 9: comment.v1.CommentService.GetComment:input_type -> comment.v1.GetCommentRequest
	6,  // 10: comment.v1.CommentService.UpdateComment:input_type -> comment.v1.UpdateCommentRequest
	8,  // 11: comment.v1.CommentService.DeleteComment:input_type -> comment.v1.DeleteCommentRequest
	10, // 12: comment.v1.CommentService.ListComments:input_type -> comment.v1.ListCommentsRequest
	12, // 13: comment.v1.CommentService.GetArticleComments:input_type -> comment.v1.GetArticleCommentsRequest
	14, // 14: comment.v1.CommentService.ReplyComment:input_type -> comment.v1.ReplyCommentRequest
	16, // 15: comment.v1.CommentService.LikeComment:input_type -> comment.v1.LikeCommentRequest
	18, // 16: comment.v1.CommentService.GetCommentReplies:input_type -> comment.v1.GetCommentRepliesRequest
	20, // 17: comment.v1.CommentService.EnableComment:input_type -> comment.v1.EnableCommentRequest
	22, // 18: comment.v1.CommentService.DisableComment:input_type -> comment.v1.DisableCommentRequest
	3,  // 19: comment.v1.CommentService.CreateComment:output_type -> comment.v1.CreateCommentResponse
	5,  // 20: comment.v1.CommentService.GetComment:output_type -> comment.v1.GetCommentResponse
	7,  // 21: comment.v1.CommentService.UpdateComment:output_type -> comment.v1.UpdateCommentResponse
	9,  // 22: comment.v1.CommentService.DeleteComment:output_type -> comment.v1.DeleteCommentResponse
	11, // 23: comment.v1.CommentService.ListComments:output_type -> comment.v1.ListCommentsResponse
	13, // 24: comment.v1.CommentService.GetArticleComments:output_type -> comment.v1.GetArticleCommentsResponse
	15, // 25: comment.v1.CommentService.ReplyComment:output_type -> comment.v1.ReplyCommentResponse
	17, // 26: comment.v1.CommentService.LikeComment:output_type -> comment.v1.LikeCommentResponse
	19, // 27: comment.v1.CommentService.GetCommentReplies:output_type -> comment.v1.GetCommentRepliesResponse
	21, // 28: comment.v1.CommentService.EnableComment:output_type -> comment.v1.EnableCommentResponse
	23, // 29: comment.v1.CommentService.DisableComment:output_type -> comment.v1.DisableCommentResponse
	19, // [19:30] is the sub-list for method output_type
	8,  // [8:19] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_comment_proto_init() }
func file_proto_comment_proto_init() {
	if File_proto_comment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_comment_proto_rawDesc), len(file_proto_comment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_comment_proto_goTypes,
		DependencyIndexes: file_proto_comment_proto_depIdxs,
		EnumInfos:         file_proto_comment_proto_enumTypes,
		MessageInfos:      file_proto_comment_proto_msgTypes,
	}.Build()
	File_proto_comment_proto = out.File
	file_proto_comment_proto_goTypes = nil
	file_proto_comment_proto_depIdxs = nil
}
